name: Release
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # pin@v3
        with:
          go-version: 1.18
      - name: Vet
        run: go vet ./...
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3
        with:
          fetch-depth: 0
      - name: Changelog
        run: |
          PREVIOUS_TAG=$(git tag | tail -2 | head -1)
          printf '## Changelog\n\n' > CHANGELOG.md
          git log --oneline --no-color $PREVIOUS_TAG..$GITHUB_REF >> CHANGELOG.md
      - name: Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # pin@v1
        with:
          body_path: CHANGELOG.md
