name: Release
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3
        with:
          go-version: 1.18
      - name: Vet
        run: go vet ./...
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3
        with:
          fetch-depth: 0
      - name: Changelog
        run: |
          PREVIOUS_TAG=$(git tag | tail -2 | head -1)
          printf '## Changelog\n\n' > CHANGELOG.md
          git log --oneline --no-color $PREVIOUS_TAG..$GITHUB_REF >> CHANGELOG.md
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # pin@v1
        with:
          body_path: CHANGELOG.md
